spring.application.name=prod-ready-features
spring.datasource.url = jdbc:postgresql://localhost:5432/prodreadyfeature?currentSchema=public
spring.datasource.username= postgres
spring.datasource.password= secure
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect